##
## deep dream docker

FROM tensorflow/tensorflow:1.6.0-devel-gpu

#RUN apt-get update & apt-get install python-tk
#RUN apt-get update & apt-get install -y libsm6 libxext6
RUN pip install argparse pillow opencv-python scipy keras keras-applications matplotlib 
